"""
Website Chat Widget API
Handles the generation of the chat widget script and inbound messages from website widgets.
"""

from fastapi import APIRouter, Request, HTTPException
from pydantic import BaseModel
from typing import Optional, List
import uuid
from datetime import datetime

from ..memory import supabase
from ..pipeline.message_pipeline import process_incoming_message

router = APIRouter(prefix="/website-chat", tags=["Website Chat"])

class WidgetConfig(BaseModel):
    business_name: str
    primary_color: str = "#3b82f6"
    welcome_message: str = "Hi! How can I help you today?"
    position: str = "right" # left or right

@router.get("/widget-script/{organization_id}")
def get_widget_script(organization_id: int):
    """
    Returns the snippet that the user needs to paste into their website.
    """
    # In a real app, this would be a URL to a hosted JS file
    base_url = "https://sap-guru-assistant.onrender.com"
    
    script = f"""
<!-- AI Command Center Chat Widget -->
<script>
  (function() {{
    var script = document.createElement('script');
    script.src = "{base_url}/static/widget.js";
    script.async = true;
    script.onload = function() {{
      window.AIChatWidget.init({{
        orgId: {organization_id},
        baseUrl: "{base_url}"
      }});
    }};
    document.head.appendChild(script);
  }})();
</script>
    """
    return {"status": "success", "script": script.strip()}

@router.post("/message")
async def receive_website_message(request: Request):
    """
    Receives a message from the website chat widget.
    """
    data = await request.json()
    
    sender_id = data.get("sender_id") # Unique ID generated by the widget (e.g. browser fingerprint or cookie)
    message_text = data.get("message", "")
    organization_id = data.get("organization_id", 1)
    
    if not sender_id or not message_text:
        raise HTTPException(status_code=400, detail="Missing sender_id or message")

    # Process through the standard AI pipeline
    pipeline_result = process_incoming_message(
        organization_id=organization_id,
        channel="website_chat",
        sender_id=sender_id,
        message_text=message_text,
        raw_payload=data
    )

    return {
        "status": "success",
        "reply": pipeline_result.get("reply", ""),
        "logs": pipeline_result.get("logs", [])
    }
